apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h73l61474-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h73l61474-java-quarkus-gitops